/*
   Name:         Peter Corcoran, PMCORCOR
   Program:      Lab 5
   Version:      1.0
   Date Started: Nov 30, 2014  


DESCRIPTION:
   Lab 5 - Analog to Digital Conversion and Serial Communication
   
   
LAB MANUAL:
   https://github.com/corcoranp/ee337/blob/master/ee337_lab_manual_v2_2.pdf
               
PRELAB:               
   Write a short, technical paragraph on why you think it is important to learn
   about serial communication. Remember to cite any sources that you use for 
   research.       
   
   

REQUIREMENTS:
   PART 1
   The main portion of this assignment is to us the HCS12 Analog to Digital 
   converter to measure the voltage generated by the potentiometer on the board. 

   - Voltage Values: 0VDC-5VDC
   - Display 8 most significant bits of measured value on 8 Port B LEDs
      - MSB of converter should appear on PB7, logical 1 should light up LED
   - Program should loop continuously in a Measure & Display cycle
   - Use potentiometer VR2 on board
      - Ensure reading input from pot not the extern input   
   
      

ADDITIONAL INFORMATION:

   
*/

#include <hidef.h>      /* common defines and macros */
#include "derivative.h"      /* derivative-specific definitions */
#include "common.h"
#include "LedControl.h"
#include "button_control.h"
//#include "acd.h"

void initialize();
void measure(void);
void display(void);
void displayDecimal(void);

bool displayOnSegment=false;

struct buttonPressState buttonState;
/*
   Main Entry point of program.
*/
void main(void) {
   initialize();
   
   while(true){
      measure();
      
      
      if(displayOnSegment){
         setSegmentLedsEnabled(true);
         setPBLedsEnabled(false); 
         displayDecimal();      
      }else{
         setSegmentLedsEnabled(false);
         setPBLedsEnabled(true); 
         display();           
      }
   }
}

/*
   Initializaiton of the Lab Assignment
*/
void initialize(){
      DisableInterrupts;      //Disables interrupts while init is running
      initSystemClock();
     
      initializeLeds();
      DDRH = 0x00;     //PTH as input
      PIEH = 0xFF;   //enable PTH interrupt
      PPSH = 0x0;   //Make it Edge-Trig.
      
      initializeACD(0);
  
      EnableInterrupts;
}

void measure(void){
   startNewADCSequence();   
}

void display(void){
   show(getData());
   //displayDecimal();
}

void displayDecimal(void){
   int raw;
   int whole;
   unsigned int dec;
   raw =getData(); 
   whole = raw*5/255;   //clips remainder
   dec = (raw-(whole*255/5))*500/255;  
   
   //show(dec); 
   showDecimal(whole, dec);   
}



//#region ----------- Interrupt CODE ----------
#pragma CODE_SEG __NEAR_SEG NON_BANKED
interrupt (((0x10000-Vporth)/2)-1) void PORTH_ISR(void)
{
   displayOnSegment =!displayOnSegment;    
   PIFH = PIFH | 0xFF;      //clear PTH Interupt Flags for the next round. Writing HIGH will clear the Interrupt flags
} 
#pragma CODE_SEG DEFAULT














